# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-epic-dag" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/ActualAdam/jira-epic-dag/releases/download/v#{version}/jira-epic-dag_#{version}_darwin_amd64.tar.gz"
      sha256 "eb6785815a5423f86e85928423741c8602fd70aad333d56cf3b5e6e5fdb0c217"
    end
    on_arm do
      url "https://github.com/ActualAdam/jira-epic-dag/releases/download/v#{version}/jira-epic-dag_#{version}_darwin_arm64.tar.gz"
      sha256 "44187532840b77250dcd204118026c66c0e9d2be7c06938f639740d3444c9105"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ActualAdam/jira-epic-dag/releases/download/v#{version}/jira-epic-dag_#{version}_linux_amd64.tar.gz"
      sha256 "df474c4c3412ef9944126c82ee18a67d5e93ce83c48af1c076f002df9c1e4e32"
    end
    on_arm do
      url "https://github.com/ActualAdam/jira-epic-dag/releases/download/v#{version}/jira-epic-dag_#{version}_linux_arm64.tar.gz"
      sha256 "53b1ec2262e110a9ac1d0490360d0ff88ab091f3c7ad72b20368891506e4a879"
    end
  end

  name "jira-epic-dag"
  desc "TUI app that visualizes Jira epic dependency graphs"
  homepage "https://github.com/ActualAdam/jira-epic-dag"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-epic-dag"

  # No zap stanza required

end
